###################################
# EconomyVault Module for GravesX #
###################################

# Should we enable this module?
enabled: true

# Default Locale (will fall back if the language is missing)
default-language: "en_us"

economy:
  currency-symbol: "$"
  round-to-decimals: 2

types:
  TELEPORT:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      fixed: 50.0
      percent: 1.0

  OPEN:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      fixed: 25.0
      percent: 0.5

  AUTOLOOT:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      fixed: 35.0
      percent: 0.75

  BLOCK_BREAK:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      fixed: 100.0
      percent: 2.0