###################################
# EconomyVault Module for GravesX #
###################################

# Should we enable this module?
enabled: true

# Default Locale (will fall back if the language is missing)
default-language: "en_us"

economy:
  # Currency symbol.
  currency-symbol: "$"
  # What to round to for the last 2 digits
  round-to-decimals: 2

# The types of grave actions
types:
  TELEPORT:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      # Fixed Balance Cost
      fixed: 50.0
      # Percent Balance Cost (Calculates from fixed balance cost)
      percent: 1.0

  OPEN:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      # Fixed Balance Cost
      fixed: 25.0
      # Percent Balance Cost (Calculates from fixed balance cost)
      percent: 0.5

  AUTOLOOT:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      # Fixed Balance Cost=
      fixed: 35.0
      # Percent Balance Cost (Calculates from fixed balance cost)
      percent: 0.75

  BLOCK_BREAK:
    enabled: true
    charge:
      # Acceptable:
      # - PERCENT_BALANCE
      # - FIXED
      mode: FIXED
      # Fixed Balance Cost
      fixed: 100.0
      # Percent Balance Cost (Calculates from fixed balance cost)
      percent: 2.0